name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, ovh]
    outputs:
      commit_sha: ${{ steps.vars.outputs.commit_sha }} 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: vars
        run: |
          COMMIT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)
          echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

      - run: echo "commit_sha=${{ env.COMMIT_SHA }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ORG_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.ORG_DOCKER_HUB_ACCESS_TOKEN }}

      #- name: Build docker image
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: .
      #    file: ./Dockerfile
      #    push: false
      #    no-cache: true
      #    tags: |
      #      ${{ secrets.ORG_DOCKER_HUB_USERNAME }}/flare-price-provider:${{ github.run_number }}