name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, ovh]
    outputs:
      commit_sha: ${{ steps.vars.outputs.commit_sha }} 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: vars
        run: |
          echo "commit_sha=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - run: echo "commit_sha=${{ build.outputs.commit_sha}}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ORG_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.ORG_DOCKER_HUB_ACCESS_TOKEN }}

      #- name: Build docker image
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: .
      #    file: ./Dockerfile
      #    push: false
      #    no-cache: true
      #    tags: |
      #      ${{ secrets.ORG_DOCKER_HUB_USERNAME }}/flare-price-provider:${{ github.run_number }}